### ISSUE TITLE
gdb.txt not found

### ISSUE THREAD

**Issue by lasyan3** [StevensND/ghidra-port-mods-guide#3]
Hey, thanks for this guide.
I tried to use it but when running the first python script it says file gdb.txt not found.
Looking at the code, I don't see how this file is generated.
Can you help please?
Thanks.

**Comment by StevensND** [comment]
https://youtu.be/yV85AgYlE5c?si=OsVyww0nNArkE9mZ&t=456

In that guide I show all the process.

**Comment by lasyan3** [comment]
ok my bad I had to enable the logging in gdb so the file is properly generated. Thanks!
